### ISSUE TITLE
RSI calculation is giving "Divide 0" exception

### ISSUE THREAD

**Issue by sagarraut0007** [lppkarl/Trady#47]
var rsi = candles.Rsi(9)[candles.Count() - 1];

Exception -> Attempted to divide by zero
StackTrace ->

   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at System.Decimal.op_Division(Decimal d1, Decimal d2)
   at Trady.Analysis.Indicator.RelativeStrength`2.ComputeByIndexImpl(IReadOnlyList`1 mappedInputs, Int32 index)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.<ComputeByIndex>b__25_0(Int32 i)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.ComputeByIndex(Int32 index)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.Map(Func`2 otmFunc, Int32 index)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.get_Item(Int32 index)
   at Trady.Analysis.Indicator.RelativeStrengthIndex`2.ComputeByIndexImpl(IReadOnlyList`1 mappedInputs, Int32 index)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.<ComputeByIndex>b__25_0(Int32 i)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.ComputeByIndex(Int32 index)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.Map(Func`2 otmFunc, Int32 index)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.get_Item(Int32 index)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.<Compute>b__7_0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.Compute(Func`2 outputFunc, Nullable`1 startIndex, Nullable`1 endIndex)
   at Trady.Analysis.Infrastructure.AnalyzableBase`4.Compute(Nullable`1 startIndex, Nullable`1 endIndex)
   at Trady.Analysis.CandlesExtension.Rsi(IEnumerable`1 candles, Int32 periodCount, Nullable`1 startIndex, Nullable`1 endIndex)
   at Kite.AutoTrading.StrategyManager.Strategy.MAStrategy.Scan(Symbol symbol, IEnumerable`1 candles, Boolean isPlaceOrder) in C:\Users\sagar.raut\source\repos\Kite.AutoTrading\Kite.AutoTrading.StrategyManager\Strategy\MAStrategy.cs:line 130
   at Kite.Autotrading.Test.MAStrategyTest.GetProfitOfDay(Symbol symbol, IEnumerable`1 candles) in C:\Users\sagar.raut\source\repos\Kite.AutoTrading\Kite.Autotrading.Test\Tests\MAStrategyTest.cs:line 154
   at Kite.Autotrading.Test.MAStrategyTest.<>c__DisplayClass2_3.<WeeklyWatchlistIsProfitableOrNot>b__0(Symbol symbol) in C:\Users\sagar.raut\source\repos\Kite.AutoTrading\Kite.Autotrading.Test\Tests\MAStrategyTest.cs:line 124
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()

**Comment by lppkarl** [comment]
Hi @sagarraut0007 , there's a relating issue on #44, this issue will be closed. It would also be good to try if v3.1.0-beta1 on nuget works and see if the bug is fixed. Thanks.
