### ISSUE TITLE
StooqImporter not work

### ISSUE THREAD

**Issue by uranio-235** [lppkarl/Trady#94]
```C#
System.AggregateException
  HResult=0x80131500
  Mensaje = One or more errors occurred.
  Origen = System.Private.CoreLib
  Seguimiento de la pila:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at playground.Program.Main(String[] args) in C:\Users\lazaro\source\repos\trading\playground\Program.cs:line 21

Excepción interna 1:
Exception: No data
```

Code simple

```C#
var grafico = new StooqImporter()
   .ImportAsync("FB", DateTime.Now - TimeSpan.FromDays(60)).Result;
```

**Comment by uranio-235** [comment]
my bad. Stoow symbols should be FB.US

any way, it return an empty dataset
